# Generated by Django 2.1 on 2018-08-13 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FestivePack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=500)),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctg_name', models.CharField(max_length=250)),
                ('img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('best_seller', models.BooleanField(default=0)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(default='0', max_length=10)),
                ('name', models.CharField(max_length=250)),
                ('subject', models.TextField(default='')),
                ('desc', models.TextField()),
                ('email', models.CharField(blank=True, max_length=250)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Products')),
            ],
        ),
    ]
