# Generated by Django 2.1 on 2018-08-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180820_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivepack',
            name='img',
            field=models.ImageField(blank=True, upload_to='FestivePack'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, upload_to='item'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
    ]
